### ISSUE TITLE
Релиз под 5-ую версию библиотеки Qt

### ISSUE THREAD

**Issue by DenisBabarykin** [DenisBabarykin/SeaBattle#1]
Перенести проект на 5-ую версию библиотеки Qt.

**Comment by efgefg0001** [comment]
Привет. Я прочитал сообщение в vk.com. Язашел на github, посмотрел структуру репозитория SeaBattle

**Comment by DenisBabarykin** [comment]
Выполнено. Иноформация по компиляции проекта под Windows и Linux в Wiki.
