### ISSUE TITLE
Исправить баг падения клиента в однопользовательской игре.

### ISSUE THREAD

**Issue by DenisBabarykin** [DenisBabarykin/SeaBattle#2]
При первых выстрелах по вражескому полю во время однопользовательской игры на любом уровне сложности клиент падает.

**Comment by efgefg0001** [comment]
Там была ошибка с выделением памяти в Solver, в методе fire.  Я вставил QVectorNeural::real input вместо Neural::real *input , поставил выделение памяти под output не в конструкторе, а в самом методе fire, присваивая output размер, равный размеру input.length() \* sizeof(Neural::real)

**Comment by efgefg0001** [comment]
Решил заменить сырой указатель на output. Для этого также использовал QVector. Ещё добавил width и height -ширину и длину поля битвы. В предыдущем исправлении была ошибка с переполнением input при долгой игре. В этом коммите я задаю размер input и output при помощи width и height. Инициализирую input, output в конструкторе.
